dispatcher_base:
  number_of_dispatchers: 4
  url: 'http://tournament-blockchain-base:8545'
  testing: true
  max_delay: 500
  warn_delay: 30
  services:
    -
      name: emulator
      transport:
        address: tournament-mock-machine-manager
        port: 50051
  main_concern:
    abi: DAppMock.json
  query_port: 3001
  confirmations: 0
# contracts that needed to be deployed to blockchain
blockchain:
  number_of_accounts: 10
  networks: '7777'
  projects:
    tournament:
      dependencies: []
      path: './'
      concerns:
        - 'DAppMock'
        - 'MatchInstantiator'
        - 'MatchManagerInstantiator'
        - 'RevealMock'
        - 'VGMock'
      migrate_from: '1'
      migrate_to: '2'