{% set players = num_players | int %}
version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ["ganache-cli", "--accounts", "{{ players }}", "--account_keys_path", "/ganache-data/keys"]
    volumes:
      - ganache_data:/ganache-data
    expose:
      - 8545
    networks:
      - ganache

  deployer:
    depends_on: [ganache]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
    volumes:
      - truffle_data:/usr/src/app/build
    networks:
      - ganache

  logger_deployer:
    depends_on: [ganache]
    image: cartesi/logger-blockchain-deployer
    volumes:
      - logger_deploy:/usr/src/app/build
    networks:
      - ganache

  logger_configurer:
     depends_on: [logger_deployer]
     image: cartesi/logger-configurer
     volumes:
       - logger_deploy:/truffle_data

  key_distributor:
    depends_on: [ganache]
    build: ./key-distributor
    volumes:
      - ganache_data:/keys
      {% for i in range(players) %}- dispatcher_data_{{ i }}:/key-{{ i }}
      {% endfor %}

{% for i in range(players) %}
  dispatcher_setup_{{ i }}:
    depends_on: [deployer]
    build: ./setup
    volumes:
      - truffle_data:/opt/cartesi/blockchain
      - dispatcher_data_{{ i }}:/opt/cartesi/dispatcher/config

  dispatcher_{{ i }}:
    depends_on: [dispatcher_setup_{{ i }}]
    build: .
    environment:
      RUST_LOG: dispatcher=trace,transaction=trace,configuration=trace,utils=trace,state=trace,compute=trace,hasher=trace,dappmock=trace,match=trace,matchmanager=trace,revealmock=trace
      DOCKER: "true"
    volumes:
      - truffle_data:/opt/cartesi/blockchain
      - dispatcher_data_0:/opt/cartesi/dispatcher/config
    networks:
      - ganache
      - node_{{ i }}

  logger_{{ i }}:
    depends_on: [logger_configurer]
    image: cartesi/logger-server
    volumes:
      - logger_deploy:/opt/cartesi/blockchain
      - logger_data_{{ i }}:/opt/cartesi/logger/data
    networks:
      ganache: {}
      node_{{ i }}:
        aliases:
          - logger

  machine_manager_{{ i }}:
    image: cartesi/machine-manager-mock
    networks:
      ganache: {}
      node_{{ i }}:
        aliases:
          - machine-manager

  anuto_server_{{ i }}:
    image: cartesi/anuto-server:develop-f4103222
    networks:
      node_{{ i }}:
        aliases:
          - anuto-server

  anuto_web_{{ i }}:
    depends_on: [anuto_server_{{ i }}]
    image: cartesi/anuto-web:develop-ee93da2d
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "{{ 8090 + i }}:80"
    networks:
      - node_{{ i }}
{% endfor %}

volumes:
  ganache_data:
  truffle_data:
  logger_deploy:
  {% for i in range(players) %}dispatcher_data_{{ i }}:
  logger_data_{{ i }}:
  {% endfor %}

networks:
  ganache:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
