concerns:
{{#each contracts}}
{{#unless @first}}
  - abi: "{{path}}"
    contract_address: "{{address}}"
    user_address: "{{../address}}"
{{/unless}}
{{/each}}
main_concern:
  abi: "{{contracts.0.path}}"
  contract_address: "{{contracts.0.address}}"
  user_address: "{{address}}"
confirmations: 0
max_delay: 500
query_port: 3001
services:
  - name: emulator
    transport:
      address: machine-manager
      port: 50051
  - name: logger
    transport:
      address: logger
      port: 50051
testing: true
url: http://ganache:8545
warn_delay: 30
